#!/usr/bin/env python3
"""
Generate secure API keys and tokens for AgentManager.

This script generates the internal security tokens that you control,
and provides guidance for external service keys.
"""

import secrets
import string
from datetime import datetime

def generate_secure_token(length=32):
    """Generate a cryptographically secure token."""
    return secrets.token_urlsafe(length)

def generate_secret_key(length=64):
    """Generate a secret key for JWT signing."""
    return secrets.token_urlsafe(length)

def generate_api_token(prefix="am", length=32):
    """Generate an API token with prefix."""
    token = secrets.token_urlsafe(length)
    return f"{prefix}_{token}"

def main():
    print("🔑 AgentManager API Key Generator")
    print("=" * 50)
    print(f"Generated on: {datetime.now().isoformat()}")
    print()
    
    # Generate internal keys
    print("🏠 INTERNAL KEYS - Generated by You:")
    print("-" * 40)
    
    server_token = generate_api_token("am_server", 32)
    secret_key = generate_secret_key(64)
    
    print(f"SERVER_API_TOKEN={server_token}")
    print(f"SECRET_KEY={secret_key}")
    print()
    
    # External service guidance
    print("🌐 EXTERNAL KEYS - From Third-Party Services:")
    print("-" * 40)
    print("OPENAI_API_KEY=sk-...")
    print("  ↳ Get from: https://platform.openai.com/api-keys")
    print("  ↳ Cost: Pay-per-use (~$0.03 per 1K tokens for GPT-4)")
    print("  ↳ Required for: LLM operations in AgentManager")
    print()
    
    # Additional security recommendations
    print("🔐 Security Recommendations:")
    print("-" * 40)
    print("1. Store these keys securely (never commit to git)")
    print("2. Use different keys for development/production")
    print("3. Rotate keys regularly in production")
    print("4. Monitor OpenAI usage to control costs")
    print("5. Set usage limits in OpenAI dashboard")
    print()
    
    # .env file template
    print("📝 Ready-to-use .env entries:")
    print("-" * 40)
    print(f"""# Internal Security (Generated {datetime.now().strftime('%Y-%m-%d')})
SERVER_API_TOKEN={server_token}
SECRET_KEY={secret_key}

# External Services (You must obtain these)
OPENAI_API_KEY=your_openai_api_key_here

# Database
DATABASE_URL=sqlite+aiosqlite:///./agent_manager.db

# Server Settings
HOST=0.0.0.0
PORT=8000
DEBUG=true
LOG_LEVEL=info""")

if __name__ == "__main__":
    main()